---
# Tasks file for ansible-role-gnome-extensions: Install Extension

- name: Install extension with gnome-extensions.
  ansible.builtin.command: "env {{ gnome_dbus_env }} gnome-extensions install --force {{ register__gnome_extension_temp.path }}/{{ gnome_extension_uuid }}.zip" # noqa no-changed-when
